---
# tasks file for ansible-patch-role
- name: Install Apache on Ubuntu servers
  apt:
    name: apache2
    state: present

- name: Start Apache 
  service:
    name: apache2
    state: started
    enabled: yes
    
- name: Update packages 
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"
